# Generated by Django 4.2 on 2024-03-10 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_plan_duration_plan_target_plan_wallet_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='duration',
            new_name='price',
        ),
    ]
