# Generated by Django 4.2 on 2024-02-10 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_challange_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='trade_status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=10),
        ),
    ]
