# Generated by Django 4.2 on 2024-02-10 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_trade_trade_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='margin',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
