# Generated by Django 4.2 on 2024-02-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_trade_margin'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='coin_amount',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
    ]
