# Generated by Django 4.2 on 2024-02-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_trade_liquidation_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='trade_status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('Liquidated', 'Liquidated')], default='OPEN', max_length=10),
        ),
    ]
