# Generated by Django 4.2 on 2024-03-01 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_alter_trade_trade_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='challange',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive'), ('completed', 'Completed'), ('failed', 'Failed'), ('expired', 'Expired')], default='active', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='todays_balance',
            field=models.IntegerField(default=0),
        ),
    ]
