# Generated by Django 4.2 on 2024-03-02 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_challange_changed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
